"""Regenerate data/lookup_istilah.yml from the KB entities file.

Run from Chatbot/bot/:  python scripts/gen_lookup.py
Reads KB_DIR (.env) or defaults to ../../Graphing/kb.
"""
import json
import os
import re
from pathlib import Path

from dotenv import find_dotenv, load_dotenv

load_dotenv(find_dotenv())

BOT_DIR = Path(__file__).resolve().parent.parent
KB_DIR = (BOT_DIR / os.getenv("KB_DIR", "../../Graphing/kb")).resolve()
OUT = BOT_DIR / "data" / "lookup_istilah.yml"

ents = json.loads((KB_DIR / "output" / "entities.json").read_text(encoding="utf-8"))

names = set()
for e in ents:
    for s in [e["name"], *e.get("aliases", [])]:
        s = s.strip()
        # keep short, clean surface forms; drop sentence-fragments
        if 1 < len(s) <= 40 and not re.search(r"[.;:()\[\]\"]|\byang\b|\byaitu\b", s):
            names.add(s.lower())

lines = "\n".join(f"    - {n}" for n in sorted(names))
OUT.write_text(
    '# AUTO-GENERATED by scripts/gen_lookup.py — do not edit by hand.\n'
    'version: "3.1"\n\n'
    "nlu:\n"
    "- lookup: istilah\n"
    "  examples: |\n"
    f"{lines}\n",
    encoding="utf-8",
)
print(f"wrote {OUT} ({len(names)} terms)")
