"""
build_sources.py -- writes the repo-root SOURCES.md: every source the KB's facts and
definitions come from, grouped by source, with the terms each one supports.

Sources:
  - the corpus files build_kb.py reads (data/ngaben-merge-cleaned.txt via the relation
    rows, data/ngaben-glossary.txt for the definitions)
  - every URL in tuning/definition_sources.json (web-sourced definitions)
  - every URL / corpus line cited by a relation row: a web row's context_sentence and
    any regional-variant row's variant.source

SOURCES.md is gitignored (local reference). Re-run whenever sources change:
    ..\\..\\..\\Chatbot\\rasa_bot\\Scripts\\python.exe build_sources.py   (from Graphing/kb/curation/)
"""
import json
import re
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
KB = HERE.parent
REPO = KB.parent.parent
ROWS = KB.parent / "neo4" / "relation_results_ngaben.normalized.json"
DEF_SOURCES = KB / "tuning" / "definition_sources.json"
ENTITIES = KB / "output" / "entities.json"
OUT = REPO / "SOURCES.md"

URL = re.compile(r"https?://[^\s;,)\"']+")
CORPUS_LINE = re.compile(r"\bL(\d{1,4})\b")


def main():
    rows = json.loads(ROWS.read_text(encoding="utf-8"))
    ents = json.loads(ENTITIES.read_text(encoding="utf-8"))
    defs = json.loads(DEF_SOURCES.read_text(encoding="utf-8"))

    web = defaultdict(lambda: {"definitions": set(), "facts": set(), "variants": set()})
    for term, src in defs.items():
        if term.startswith("_"):
            continue
        for url in URL.findall(str(src)):
            web[url.rstrip(".")]["definitions"].add(term)

    corpus_rows, corpus_terms = 0, set()
    for r in rows:
        ctx = r.get("context_sentence", "")
        triple = f"{r['subject']} {r['relation']} {r['object']}"
        for url in URL.findall(ctx):
            web[url.rstrip(".")]["facts"].add(triple)
        v = r.get("variant") or {}
        for url in URL.findall(str(v.get("source", ""))):
            web[url.rstrip(".")]["variants"].add(f"{triple} ({v.get('region')}, {v.get('op')})")
        if not URL.search(ctx) and not URL.search(str(v.get("source", ""))):
            corpus_rows += 1
            corpus_terms.update((r["subject"], r["object"]) if r.get("object_type") == "ENTITY"
                                else (r["subject"],))

    glossary_terms = sorted(e["name"] for e in ents if e.get("definition_source") == "glossary")

    L = ["# Sources", "",
         "Every source the Ngaben KB's facts and definitions come from. Generated by "
         "`Graphing/kb/curation/build_sources.py`; do not edit by hand. Web-sourced items are "
         "UNREVIEWED unless `Graphing/kb/tuning/definition_sources.json` `_approved` names them.", "",
         "## Corpus", "",
         f"- `Graphing/data/ngaben-merge-cleaned.txt` -- the merged Ngaben source text; "
         f"{corpus_rows} relation rows (extracted or hand-curated, cited by line as Lnnnn) "
         f"over {len(corpus_terms)} terms.",
         f"- `Graphing/data/ngaben-glossary.txt` -- the glossary definitions of {len(glossary_terms)} entities.",
         "",
         f"## Web ({len(web)} pages)", ""]
    for url in sorted(web):
        w = web[url]
        L.append(f"### {url}")
        L.append("")
        if w["definitions"]:
            L.append(f"- definitions: {', '.join(sorted(w['definitions']))}")
        if w["facts"]:
            L.append(f"- facts ({len(w['facts'])}): {'; '.join(sorted(w['facts']))}")
        if w["variants"]:
            L.append(f"- regional variants ({len(w['variants'])}): {'; '.join(sorted(w['variants']))}")
        L.append("")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: {len(web)} web pages, {corpus_rows} corpus rows")


if __name__ == "__main__":
    main()
