"""
sarana_composition_report.py -- writes sarana_composition_report.md: every sarana, tirtha and
building in the KB with its composition breakdown ("terbuat dari apa"), the tree depth, where
each edge comes from (corpus line or web page), its regional variants, and the items with none.

The tree is the one the bot shows (kb_content.KbContent.composition_tree). Run after build_kb.py:
    ..\\..\\..\\Chatbot\\rasa_bot\\Scripts\\python.exe sarana_composition_report.py   (from Graphing/kb/curation/)
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
KB = HERE.parent
sys.path.insert(0, str(KB.parent.parent / "Chatbot" / "bot"))
from kb_content import COMPOSITE_TYPES, PART_IS_SUBJECT, KbContent  # noqa: E402

OUT = HERE / "sarana_composition_report.md"
WAIVERS = KB / "tuning" / "lint_waivers.json"
URL = re.compile(r"https?://[^\s\"']+")
LINE = re.compile(r"\bL(\d{1,4})\b")


def source_of(fact):
    ctx = fact.get("source_sentence", "")
    v = fact.get("variant") or {}
    u = URL.search(ctx) or URL.search(str(v.get("source", "")))
    if u:
        return "web", u.group(0)
    m = LINE.search(ctx)
    return "corpus", (f"L{m.group(1)}" if m else f"sid {fact['sentence_id']}")


def main():
    kb = KbContent(KB)
    ents = json.loads((KB / "output" / "entities.json").read_text(encoding="utf-8"))
    waived = json.loads(WAIVERS.read_text(encoding="utf-8")).get("comp_leaves", {})
    # (whole, part) -> fact, to cite each edge
    fact_of = {}
    for rows in kb.facts_by_subj.values():
        for f in rows:
            fact_of.setdefault((f["subject_id"], f["object_id"]), f)

    def cite(whole, part):
        f = fact_of.get((whole, part)) or fact_of.get((part, whole))
        return source_of(f) if f else ("?", "")

    def depth(node):
        return 1 + max((depth(p["node"]) for p in node["parts"]), default=0) if node["parts"] else 0

    scope = sorted((e for e in ents if e.get("type") in COMPOSITE_TYPES), key=lambda e: e["name"])
    status, sections, srcs = Counter(), [], Counter()
    for e in scope:
        eid = e["id"]
        if kb.is_raw(eid):
            status["raw"] += 1
            continue
        if eid in waived:
            status["waived"] += 1
            sections.append((eid, f"### {e['name']}\n\nNo breakdown (waived): {waived[eid]}\n"))
            continue
        tree = kb.composition_tree(eid)
        if not tree["parts"]:
            status["none"] += 1
            sections.append((eid, f"### {e['name']}\n\n**No breakdown recorded.**\n"))
            continue
        status["inherited" if tree["inherited_from"] else "own"] += 1
        lines = [f"### {e['name']}", "",
                 f"depth {depth(tree)}" + (f"; shown via its kind-parent **{tree['inherited_from']}**"
                                            if tree["inherited_from"] else ""), ""]
        queue = [tree]
        while queue:
            node = queue.pop(0)
            whole = kb.id_by_name.get(node["inherited_from"]) if node.get("inherited_from") else node["id"]
            for p in node["parts"]:
                child = p["node"]
                kind, ref = cite(whole, child["id"])
                srcs[kind] += 1
                v = p.get("variant")
                tag = (f" -- VARIANT {v.get('op')} [{v.get('region')}]" + (f" replaces {v['replaces']}" if v.get("replaces") else "")
                       if v else "")
                leaf = " (raw)" if child["raw"] else (" (no parts)" if not child["parts"] and not child["seen"] else "")
                edge = (f"**{child['name']}**{leaf} {p['predicate']} {node['name']}" if p["predicate"] in PART_IS_SUBJECT
                        else f"{node['name']} {p['predicate']} **{child['name']}**{leaf}")
                lines.append(f"- {edge}{tag} -- {kind} {ref}")
                if child["parts"]:
                    queue.append(child)
        sections.append((eid, "\n".join(lines) + "\n"))

    L = ["# Sarana composition report", "",
         "Generated by `sarana_composition_report.py` from the current KB build. Every sarana, tirtha "
         "and building, with the breakdown the bot shows for \"X terbuat dari apa\". Web edges are "
         "UNREVIEWED unless `tuning/definition_sources.json` `_approved` names them.", "",
         f"- in scope: {len(scope)}",
         f"- raw materials (leaves): {status['raw']}",
         f"- broken down by their own edges: {status['own']}",
         f"- shown through their kind-parent: {status['inherited']}",
         f"- waived (not a made object, class name, open conflict): {status['waived']}",
         f"- **no breakdown**: {status['none']}",
         f"- edges cited: corpus {srcs['corpus']}, web {srcs['web']}, unknown {srcs['?']}", ""]
    L += [s for _, s in sections]
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: {dict(status)}; edges {dict(srcs)}")


if __name__ == "__main__":
    main()
